### ISSUE TITLE
Cannot open any challenge

### ISSUE THREAD

**Issue by TarushS** [stormctf/CTFd-Theme-StormCTF#3]
I cannot open challenges when i click on 'open challenges' button.
There is nowhere to click when opened challenge.

**Comment by TarushS** [comment]
When i was randomly clicking, i noticed that some text got copied and found out that challenge does open but without any window.

**Comment by stormctf** [comment]
This is because you didn't copy the challenge templates over. You have to replace them in the challenge plugins folder.

**Comment by TarushS** [comment]
I did but standard are opening but not dynamic ones

**Comment by stormctf** [comment]
You have another issue open for that. Closed this one :)
